In [1]:
import asyncio
import logging
import os
from pathlib import Path
import yaml
import pandas as pd
from typing import Dict, Any, Tuple, List, Optional
from dotenv import load_dotenv
import argparse
from datetime import datetime

from src.factories.clothing_factory import ClothingFactory
from src.services.api_service import APIService
from src.services.attribute_generator import AttributeGenerator
from src.services.batch_processor import BatchProcessor
from src.utils.logging_utils import (
    setup_logging, 
    LoggingContext, 
    PerformanceMetrics,
    StructuredLogger
)
from src.services.product_standardizer import ProductStandardizer
from src.base.clothing_item import ClothingItem

In [2]:
from abc import ABC, abstractmethod
from enum import Enum
from typing import List, Dict, Any, Union
import re
import logging
from pydantic import (
    BaseModel, Field, field_validator, ValidationInfo
)
from src.base.enums import (
    Color, ColorDetailed, Pattern, Material, 
    EmbellishmentLevel, Embellishment, Occasion, 
    Style, Gender, AgeGroup
)
from src.utils.validation import validate_enum_field, validate_enum_list
from src.utils.config_loader import ConfigManager
import pandas as pd

In [3]:
class ConfigLoader:
    def __init__(self, config_dir: Path):
        self.config_dir = config_dir
        
    def load(self) -> Dict[str, Any]:
        """Load base configuration from YAML file"""
        config_path = self.config_dir / "base_config.yaml"
        with open(config_path) as f:
            return yaml.safe_load(f)


def load_config(config_path: str) -> Dict:
    with open(config_path) as f:
        return yaml.safe_load(f)

In [4]:
ClothingFactory.initialize()

## Load products

In [10]:
base_path = '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/product_attributes/config/base_config.yaml'
config = load_config(base_path)
from src.utils.config_loader import ConfigManager

In [11]:
def load_and_prepare_data(config: Dict) -> Tuple[pd.DataFrame, Dict]:
    input_path = config["paths"]["input"]["product_data"]
    
    # Read CSV with product_id as string
    df = pd.read_csv(
        input_path,
        dtype={
            "Product ID": str,  # Force product_id to be string
            "Brand Name": str,
            "Product Type": str,
            "Product Name": str,
            "Product Description": str,
            "Product Image Link": str,
            "Price": float,
            "Size": str,
            "Tags": str,
            "Product URL": str
        }
    )
    
    # Define column mappings
    column_mappings = {
        "Brand Name": "brand_name",
        "Product ID": "product_id", 
        "Product Type": "product_type",
        "Product Name": "title",
        "Product Description": "description",
        "Product Image Link": "product_image_link",
        "Price": "price",
        "Size": "size",
        "Tags": "tags",
        "Product URL": "product_url"
    }
    
    # Rename columns
    df = df.rename(columns=column_mappings)
    
    # Ensure product_id is string type
    df['product_id'] = df['product_id'].astype(str)
    
    # Remove any .0 suffix from product IDs if they were originally floats
    df['product_id'] = df['product_id'].apply(
        lambda x: x.rstrip('.0') if x.endswith('.0') else x
    )
    
    # Standardize product types for all products
    df['standardized_category'] = df['product_type'].apply(
        lambda x: ProductStandardizer.standardize_product(
            {'product_type': x}
        )['standardized_category']
    )
    
    # Get image paths
    image_paths = {}
    images_dir = Path(config["paths"]["input"].get("images_dir")) 
    if 'brand' in config.get('attributes', {}):
        images_dir = images_dir / config['attributes']['brand']['default']
    
    if images_dir and images_dir.exists():
        for product_id in df["product_id"]:
            potential_paths = [
                images_dir / f"{product_id}.jpg",
                images_dir / f"{product_id}.png",
                images_dir / f"{product_id}.webp",
                images_dir / product_id / "main.jpg",
                images_dir / product_id / "main.png"
            ]
            
            for path in potential_paths:
                if path.exists():
                    image_paths[product_id] = str(path)
                    break
    
    return df, image_paths


def filter_products(
    df: pd.DataFrame,
    available_types: List[str],
    target_types: Optional[List[str]] = None
) -> pd.DataFrame:
    """
    Filter products based on standardized product categories.
    """
    available_types = [t.title() for t in available_types]

    # Standardize all product types
    df['standardized_category'] = df['product_type'].apply(
        lambda x: ProductStandardizer.standardize_product({'product_type': x})['standardized_category']
    )
    
    # If target types specified, filter for those first
    if target_types:
        target_standardized = [
            ProductStandardizer.standardize_product({'product_type': t})['standardized_category']
            for t in target_types
        ]
        target_standardized = list(set(target_standardized))
        filtered_df = df[df['standardized_category'].isin(target_standardized)]
    else:
        filtered_df = df.copy()

    # Split into standard and non-standard products
    standard_products = filtered_df[filtered_df['standardized_category'].isin(available_types)]
    other_products = filtered_df[~filtered_df['standardized_category'].isin(available_types)]
    
    if not other_products.empty:
        print(
            f"Found {len(other_products)} products with non-standard categories. "
            "Will use base configuration for these."
        )
        
    # Combine both dataframes, maintaining the separation via standardized_category
    filtered_df = pd.concat([standard_products, other_products])
    
    # Log distribution
    if not filtered_df.empty:
        type_counts = filtered_df['standardized_category'].value_counts().to_dict()
        print(
            f"Category distribution {type_counts}"
        )
    
    return filtered_df

In [25]:
input_path = config["paths"]["input"]["product_data"]

# Read CSV with product_id as string
df = pd.read_csv(
    input_path,
    dtype={
        "Product ID": str,  # Force product_id to be string
        "Brand Name": str,
        "Product Type": str,
        "Product Name": str,
        "Product Description": str,
        "Product Image Link": str,
        "Price": float,
        "Size": str,
        "Tags": str,
        "Product URL": str
    }
)

# Define column mappings
column_mappings = {
    "Brand Name": "brand_name",
    "Product ID": "product_id", 
    "Product Type": "product_type",
    "Product Name": "title",
    "Product Description": "description",
    "Product Image Link": "product_image_link",
    "Price": "price",
    "Size": "size",
    "Tags": "tags",
    "Product URL": "product_url"
}

# Rename columns
df = df.rename(columns=column_mappings)

# Ensure product_id is string type
df['product_id'] = df['product_id'].astype(str)

# Remove any .0 suffix from product IDs if they were originally floats
df['product_id'] = df['product_id'].apply(
    lambda x: x.rstrip('.0') if x.endswith('.0') else x
)

# Standardize product types for all products
df['standardized_category'] = df['product_type'].apply(
    lambda x: ProductStandardizer.standardize_product(
        {'product_type': x}
    )['standardized_category']
)

# Get image paths
# Initialize empty dict for image paths
image_paths = {}

# Get images directory path
images_dir = Path(config["paths"]["input"].get("images_dir"))
if 'brand' in config.get('attributes', {}):
    images_dir = images_dir / config['attributes']['brand']['default']

# Debug prints
print(f"Images directory path: {images_dir}")
print(f"Images directory exists: {images_dir.exists()}")

if images_dir and images_dir.exists():
    print("Directory exists")
    print(f"Number of product IDs to process: {len(df['product_id'])}")
    
    for product_id in df["product_id"]:
        potential_paths = [
            images_dir / f"{product_id}.jpg",
            images_dir / f"{product_id}.png", 
            images_dir / f"{product_id}.webp",
            images_dir / product_id / "main.jpg",
            images_dir / product_id / "main.png"
        ]
        
        # Debug print paths being checked
        print(f"\nChecking paths for product {product_id}:")
        for path in potential_paths:
            print(f"Checking {path}, exists: {path.exists()}")
            if path.exists():
                image_paths[product_id] = str(path)
                print(f"Found image at {path}")
                break

print(f"\nTotal images found: {len(image_paths)}")

Images directory path: /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta
Images directory exists: True
Directory exists
Number of product IDs to process: 4888

Checking paths for product 7355069300801:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355069300801.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355069300801.jpg

Checking paths for product 7372922781761:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372922781761.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372922781761.jpg

Checking paths for product 7372876546113:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372876546113.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372876546113.jpg

Checking paths for product 7372801835073:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372801835073.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372801835073.jpg

Checking paths for product 7372794265665:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372794265665.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372794265665.jpg

Checking paths for product 7372774015041:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372774015041.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372774015041.jpg

Checking paths for product 7372733612097:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372733612097.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372733612097.jpg

Checking paths for product 7372297961537:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372297961537.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372297961537.jpg

Checking paths for product 7372103680065:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372103680065.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372103680065.jpg

Checking paths for product 7372085952577:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372085952577.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372085952577.jpg

Checking paths for product 7370781982785:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7370781982785.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7370781982785.jpg

Checking paths for product 7366525386817:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7366525386817.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7366525386817.jpg

Checking paths for product 7366325338177:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7366325338177.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7366325338177.jpg

Checking paths for product 7365360386113:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7365360386113.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7365360386113.jpg

Checking paths for product 7365357371457:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7365357371457.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7365357371457.jpg

Checking paths for product 7364955766849:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364955766849.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364955766849.jpg

Checking paths for product 7364933845057:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364933845057.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364933845057.jpg

Checking paths for product 7364800938049:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364800938049.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364800938049.jpg

Checking paths for product 7364079747137:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364079747137.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364079747137.jpg

Checking paths for product 7363857317953:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7363857317953.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7363857317953.jpg

Checking paths for product 7363845226561:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7363845226561.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7363845226561.jpg

Checking paths for product 7362761228353:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7362761228353.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7362761228353.jpg

Checking paths for product 7361566801985:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361566801985.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361566801985.jpg

Checking paths for product 7361564999745:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361564999745.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361564999745.jpg

Checking paths for product 7361562738753:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361562738753.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361562738753.jpg

Checking paths for product 7358914330689:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358914330689.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358914330689.jpg

Checking paths for product 7358899683393:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358899683393.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358899683393.jpg

Checking paths for product 7358893260865:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358893260865.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358893260865.jpg

Checking paths for product 7358880940097:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358880940097.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358880940097.jpg

Checking paths for product 7358877827137:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358877827137.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358877827137.jpg

Checking paths for product 7358876319809:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358876319809.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358876319809.jpg

Checking paths for product 7358870814785:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358870814785.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358870814785.jpg

Checking paths for product 7357107273793:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7357107273793.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7357107273793.jpg

Checking paths for product 7357060677697:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7357060677697.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7357060677697.jpg

Checking paths for product 7356954902593:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356954902593.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356954902593.jpg

Checking paths for product 7356404695105:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356404695105.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356404695105.jpg

Checking paths for product 7356361736257:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356361736257.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356361736257.jpg

Checking paths for product 7356208873537:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356208873537.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356208873537.jpg

Checking paths for product 7355317452865:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355317452865.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355317452865.jpg

Checking paths for product 7355313029185:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355313029185.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355313029185.jpg

Checking paths for product 7355312439361:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355312439361.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355312439361.jpg

Checking paths for product 7355296153665:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355296153665.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355296153665.jpg

Checking paths for product 7355294810177:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355294810177.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355294810177.jpg

Checking paths for product 7355207450689:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355207450689.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355207450689.jpg

Checking paths for product 7355187593281:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355187593281.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355187593281.jpg

Checking paths for product 7355158724673:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355158724673.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355158724673.jpg

Checking paths for product 7355124645953:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355124645953.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355124645953.jpg

Checking paths for product 7355082211393:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355082211393.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355082211393.jpg

Checking paths for product 7355079950401:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355079950401.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355079950401.jpg

Checking paths for product 7355076804673:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355076804673.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355076804673.jpg

Checking paths for product 7384581242945:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384581242945.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384581242945.jpg

Checking paths for product 7384579571777:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384579571777.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384579571777.jpg

Checking paths for product 7384578097217:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384578097217.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384578097217.jpg

Checking paths for product 7384577802305:
Checking /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384577802305.jpg, exists: True
Found image at /Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384577802305.jpg

Checking paths for product 7384416649281:

In [27]:
image_paths

{'7355069300801': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355069300801.jpg',
 '7372922781761': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372922781761.jpg',
 '7372876546113': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372876546113.jpg',
 '7372801835073': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372801835073.jpg',
 '7372794265665': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372794265665.jpg',
 '7372774015041': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372774015041.jpg',
 '7372733612097': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372733612097.jpg',
 '7372297961537': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372297961537.jpg',
 '7372103680065': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372103680065.jpg',
 '7372085952577': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7372085952577.jpg',
 '7370781982785': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7370781982785.jpg',
 '7366525386817': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7366525386817.jpg',
 '7366325338177': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7366325338177.jpg',
 '7365360386113': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7365360386113.jpg',
 '7365357371457': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7365357371457.jpg',
 '7364955766849': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364955766849.jpg',
 '7364933845057': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364933845057.jpg',
 '7364800938049': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364800938049.jpg',
 '7364079747137': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7364079747137.jpg',
 '7363857317953': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7363857317953.jpg',
 '7363845226561': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7363845226561.jpg',
 '7362761228353': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7362761228353.jpg',
 '7361566801985': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361566801985.jpg',
 '7361564999745': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361564999745.jpg',
 '7361562738753': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7361562738753.jpg',
 '7358914330689': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358914330689.jpg',
 '7358899683393': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358899683393.jpg',
 '7358893260865': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358893260865.jpg',
 '7358880940097': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358880940097.jpg',
 '7358877827137': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358877827137.jpg',
 '7358876319809': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358876319809.jpg',
 '7358870814785': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7358870814785.jpg',
 '7357107273793': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7357107273793.jpg',
 '7357060677697': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7357060677697.jpg',
 '7356954902593': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356954902593.jpg',
 '7356404695105': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356404695105.jpg',
 '7356361736257': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356361736257.jpg',
 '7356208873537': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7356208873537.jpg',
 '7355317452865': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355317452865.jpg',
 '7355313029185': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355313029185.jpg',
 '7355312439361': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355312439361.jpg',
 '7355296153665': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355296153665.jpg',
 '7355294810177': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355294810177.jpg',
 '7355207450689': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355207450689.jpg',
 '7355187593281': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355187593281.jpg',
 '7355158724673': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355158724673.jpg',
 '7355124645953': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355124645953.jpg',
 '7355082211393': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355082211393.jpg',
 '7355079950401': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355079950401.jpg',
 '7355076804673': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7355076804673.jpg',
 '7384581242945': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384581242945.jpg',
 '7384579571777': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384579571777.jpg',
 '7384578097217': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384578097217.jpg',
 '7384577802305': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384577802305.jpg',
 '7384416649281': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384416649281.jpg',
 '7384415797313': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384415797313.jpg',
 '7384413700161': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384413700161.jpg',
 '7384410816577': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384410816577.jpg',
 '7384407310401': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384407310401.jpg',
 '7384403083329': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384403083329.jpg',
 '7384363466817': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7384363466817.jpg',
 '7382755147841': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7382755147841.jpg',
 '7382755115073': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7382755115073.jpg',
 '7382699900993': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7382699900993.jpg',
 '7382646849601': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7382646849601.jpg',
 '7382209658945': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7382209658945.jpg',
 '7381119860801': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7381119860801.jpg',
 '7377478844481': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7377478844481.jpg',
 '7377474781249': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7377474781249.jpg',
 '7375303737409': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375303737409.jpg',
 '7375299084353': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375299084353.jpg',
 '7375295250497': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375295250497.jpg',
 '7375295217729': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375295217729.jpg',
 '7375295184961': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375295184961.jpg',
 '7375295152193': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375295152193.jpg',
 '7375295119425': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375295119425.jpg',
 '7375277719617': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375277719617.jpg',
 '7375274901569': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375274901569.jpg',
 '7375270281281': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375270281281.jpg',
 '7375269232705': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375269232705.jpg',
 '7375267102785': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375267102785.jpg',
 '7375266119745': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375266119745.jpg',
 '7375265595457': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375265595457.jpg',
 '7375264645185': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375264645185.jpg',
 '7375263072321': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375263072321.jpg',
 '7375262187585': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375262187585.jpg',
 '7375204909121': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375204909121.jpg',
 '7375204352065': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375204352065.jpg',
 '7375204089921': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375204089921.jpg',
 '7375193899073': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375193899073.jpg',
 '7375189082177': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375189082177.jpg',
 '7375182463041': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375182463041.jpg',
 '7375164506177': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375164506177.jpg',
 '7375156379713': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375156379713.jpg',
 '7375154053185': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375154053185.jpg',
 '7375153430593': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375153430593.jpg',
 '7375150055489': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375150055489.jpg',
 '7375149596737': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375149596737.jpg',
 '7375143206977': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375143206977.jpg',
 '7375142617153': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7375142617153.jpg',
 '7374701920321': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374701920321.jpg',
 '7374631993409': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374631993409.jpg',
 '7374610235457': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374610235457.jpg',
 '7374591164481': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374591164481.jpg',
 '7374570389569': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374570389569.jpg',
 '7374551679041': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374551679041.jpg',
 '7374550466625': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374550466625.jpg',
 '7374550433857': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374550433857.jpg',
 '7374544142401': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374544142401.jpg',
 '7374540046401': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374540046401.jpg',
 '7374072053825': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374072053825.jpg',
 '7374056095809': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374056095809.jpg',
 '7374055473217': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374055473217.jpg',
 '7374054686785': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374054686785.jpg',
 '7374054326337': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374054326337.jpg',
 '7374053670977': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374053670977.jpg',
 '7374053408833': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374053408833.jpg',
 '7374047772737': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374047772737.jpg',
 '7374044692545': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374044692545.jpg',
 '7374043086913': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7374043086913.jpg',
 '7373823049793': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7373823049793.jpg',
 '7373716619329': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta/7373716619329.jpg',

In [21]:
images_dir

PosixPath('/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images/suta')

In [29]:
target_types = ['jacket']
available_types = ['dress', 'saree', 'kurta', 'dupatta', 'trouser', 'blouse', 'shirt', 'lehenga']

In [30]:
available_types = [t.title() for t in available_types]
# Standardize all product types
df['standardized_category'] = df['product_type'].apply(
    lambda x: ProductStandardizer.standardize_product({'product_type': x})['standardized_category']
)

# If target types specified, filter for those first
if target_types:
    target_standardized = [
        ProductStandardizer.standardize_product({'product_type': t})['standardized_category']
        for t in target_types
    ]
    target_standardized = list(set(target_standardized))
    filtered_df = df[df['standardized_category'].isin(target_standardized)]
else:
    filtered_df = df.copy()

# # Split into standard and non-standard products
standard_products = filtered_df[filtered_df['standardized_category'].isin(available_types)]
other_products = filtered_df[~filtered_df['standardized_category'].isin(available_types)]

if not other_products.empty:
    print(
        f"Found {len(other_products)} products with non-standard categories. "
        "Will use base configuration for these."
    )
    
# Combine both dataframes, maintaining the separation via standardized_category
filtered_df = pd.concat([standard_products, other_products])

# Log distribution
if not filtered_df.empty:
    type_counts = filtered_df['standardized_category'].value_counts().to_dict()
    print(
        f"Category distribution {type_counts}"
    )

Found 11 products with non-standard categories. Will use base configuration for these.
Category distribution {'Jacket': 11}

In [27]:
other_products

Empty DataFrame
Columns: [brand_name, product_id, product_type, title, description, product_image_link, price, size, tags, product_url, standardized_category]
Index: []

In [8]:
from src.base.clothing_item import ClothingItem 
# patterns, default_strategy = ClothingItem.get_category_mapping()

In [9]:
config = ConfigManager.get_base_config()
standardization_config = config.get('category_standardization', {})

patterns = []
for item in standardization_config.get('patterns', []):
    try:
        combined_pattern = r'\b(?:{})\b'.format('|'.join(item['matches']))
        compiled_pattern = re.compile(combined_pattern, re.IGNORECASE)
        patterns.append((compiled_pattern, item['name'].title()))
    except re.error as e:
        print(f"Invalid regex pattern for {item['name']}: {e}")
        continue

In [22]:
df

,brand_name,product_id,product_type,title,description,product_image_link,price,size,tags,product_url,standardized_category
0,suta,7355069300801,Rakhi,Sneh ka dhaaga,Details Dimension of Rakhi : Length - 0.45 m (...,['https://cdn.shopify.com/s/files/1/0026/6544/...,350.0,['Default Title'],"Accessories, BLUE, Colour_Blue, discount_appli...",https://suta.in/products/sneh-ka-dhaaga-rakhi,Rakhi
1,suta,7372922781761,garage_saree,GAR-1967,DetailsLength: 5.50 m (550.00 cm) ; Width: 1....,['https://cdn.shopify.com/s/files/1/0026/6544/...,2765.0,['Default Title'],"Colour_Multicolour, Fabric_Mul Cotton, lgsy_no...",https://suta.in/products/gar-1967,Saree
2,suta,7372876546113,garage_saree,GAR-1960,DetailsLength: 5.50 m (550.00 cm) ; Width: 1....,['https://cdn.shopify.com/s/files/1/0026/6544/...,2520.0,['Default Title'],"BLUE, Blue Saree, Blue Sari, Blue Saris, Colou...",https://suta.in/products/gar-1960,Saree
3,suta,7372801835073,garage_saree,GAR-1955,DetailsLength: 5.30 m (530.00 cm) ; Width: 1....,['https://cdn.shopify.com/s/files/1/0026/6544/...,16940.0,['Default Title'],"Colour_White, Fabric_Organza, lgsy_non_exchang...",https://suta.in/products/gar-1955,Saree
4,suta,7372794265665,garage_saree,GAR-1954,DetailsLength: 5.45 m (545.00 cm) ; Width: ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,3255.0,['Default Title'],"Colour_Pink, Fabric_Modal Viscose, lgsy_non_ex...",https://suta.in/products/gar-1954,Saree
...,...,...,...,...,...,...,...,...,...,...,...
4883,suta,7385414500417,Saree,Kumkum Laali,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,3800.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/kumkum-laali-saree,Saree
4884,suta,7385412829249,Saree,Laal Joba,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,9200.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/laal-joba-saree,Saree
4885,suta,7385411059777,Saree,Pujo Pujo Gondho,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,5200.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/pujo-pujo-gondho-saree,Saree
4886,suta,7385406832705,Saree,Roktima,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,3450.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/roktima-saree,Saree
4887,suta,7384583045185,Saree,Shonar Chand,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,4200.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/shonar-chand-saree,Saree

In [21]:
temp = filter_products(df,available_types = ['dress', 'saree', 'kurta', 'dupatta', 'trouser', 'blouse', 'shirt', 'lehenga']) 
temp

Found 4888 products with non-standard categories. Will use base configuration for these.
Category distribution {'Saree': 2670, 'Blouse': 1221, 'Kurta': 155, 'Dress': 154, 'Accessories': 148, 'Fabric': 85, 'Underskirt': 63, 'Combo Sets': 60, 'Shirt': 59, '': 48, 'Home Textiles': 35, 'Skirt': 32, 'Dupatta': 31, 'Trouser': 20, 'Co-Ord Set': 18, 'Rakhi': 14, 'Painting': 13, 'Mittens': 11, 'Lehenga': 11, 'Jacket': 11, 'Handkerchief/Table Napkin': 8, 'Gift Items': 7, 'Mask Chain': 4, 'Bag': 4, 'Gamcha': 2, 'Shorts': 1, 'Underlay Top': 1, 'Underlay Pant': 1, 'Handkerchief': 1}

,brand_name,product_id,product_type,title,description,product_image_link,price,size,tags,product_url,standardized_category
0,suta,7355069300801,Rakhi,Sneh ka dhaaga,Details Dimension of Rakhi : Length - 0.45 m (...,['https://cdn.shopify.com/s/files/1/0026/6544/...,350.0,['Default Title'],"Accessories, BLUE, Colour_Blue, discount_appli...",https://suta.in/products/sneh-ka-dhaaga-rakhi,Rakhi
1,suta,7372922781761,garage_saree,GAR-1967,DetailsLength: 5.50 m (550.00 cm) ; Width: 1....,['https://cdn.shopify.com/s/files/1/0026/6544/...,2765.0,['Default Title'],"Colour_Multicolour, Fabric_Mul Cotton, lgsy_no...",https://suta.in/products/gar-1967,Saree
2,suta,7372876546113,garage_saree,GAR-1960,DetailsLength: 5.50 m (550.00 cm) ; Width: 1....,['https://cdn.shopify.com/s/files/1/0026/6544/...,2520.0,['Default Title'],"BLUE, Blue Saree, Blue Sari, Blue Saris, Colou...",https://suta.in/products/gar-1960,Saree
3,suta,7372801835073,garage_saree,GAR-1955,DetailsLength: 5.30 m (530.00 cm) ; Width: 1....,['https://cdn.shopify.com/s/files/1/0026/6544/...,16940.0,['Default Title'],"Colour_White, Fabric_Organza, lgsy_non_exchang...",https://suta.in/products/gar-1955,Saree
4,suta,7372794265665,garage_saree,GAR-1954,DetailsLength: 5.45 m (545.00 cm) ; Width: ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,3255.0,['Default Title'],"Colour_Pink, Fabric_Modal Viscose, lgsy_non_ex...",https://suta.in/products/gar-1954,Saree
...,...,...,...,...,...,...,...,...,...,...,...
4883,suta,7385414500417,Saree,Kumkum Laali,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,3800.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/kumkum-laali-saree,Saree
4884,suta,7385412829249,Saree,Laal Joba,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,9200.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/laal-joba-saree,Saree
4885,suta,7385411059777,Saree,Pujo Pujo Gondho,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,5200.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/pujo-pujo-gondho-saree,Saree
4886,suta,7385406832705,Saree,Roktima,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,3450.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/roktima-saree,Saree
4887,suta,7384583045185,Saree,Shonar Chand,DetailsLength: 5.50 m (550 cm) ; Width: 1.143 ...,['https://cdn.shopify.com/s/files/1/0026/6544/...,4200.0,['Default Title'],"__with:pre-drape-this-saree, Agomoni, Agomoni ...",https://suta.in/products/shonar-chand-saree,Saree

In [ ]:
filter

## Count products

In [8]:
#!/usr/bin/env python3

import json
import os
from typing import Dict, Any, Optional


def float_hook(dct: dict) -> dict:
    for k, v in dct.items():
        if isinstance(v, str):
            try:
                if 'e' in v.lower():
                    dct[k] = float(v)
            except ValueError:
                pass
        elif isinstance(v, list):
            for i, item in enumerate(v):
                if isinstance(item, str) and 'e' in item.lower():
                    try:
                        v[i] = float(item)
                    except ValueError:
                        pass
    return dct


def count_unique_products(file_path: str) -> int:
    try:
        all_data = {}
        current_obj = ""
        brace_count = 0
        total_objects_found = 0
        failed_objects = 0
        
        with open(file_path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                    
                brace_count += line.count('{') - line.count('}')
                current_obj += line
                
                if brace_count == 0 and current_obj:
                    total_objects_found += 1
                    try:
                        data = json.loads(current_obj, object_hook=float_hook)
                        if data:
                            product_id = next(iter(data))
                            all_data[product_id] = data[product_id]
                    except json.JSONDecodeError:
                        failed_objects += 1
                        preview_len = 75
                        truncated = len(current_obj) > preview_len
                        preview = current_obj[:preview_len]
                        if truncated:
                            preview += "..."
                        obj_num = total_objects_found
                        print(f"\nFailed to parse object {obj_num}:")
                        print(preview)
                    current_obj = ""
        
        product_count = len(all_data)
        print("\nParsing Statistics:")
        print(f"Total JSON objects found: {total_objects_found}")
        print(f"Failed to parse: {failed_objects}")
        print(f"Unique products found: {product_count}")
        
        if product_count > 0:
            print("\nFirst few product IDs found:")
            for pid in list(all_data.keys())[:5]:
                print(f"- {pid}")
                
        return product_count
            
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return 0
    except Exception as e:
        print(f"Error: {str(e)}")
        return 0


def load_product_by_id(file_path: str, product_id: str) -> Optional[Dict[str, Any]]:
    try:
        current_obj = ""
        brace_count = 0
        
        with open(file_path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                    
                brace_count += line.count('{') - line.count('}')
                current_obj += line
                
                if brace_count == 0 and current_obj:
                    try:
                        data = json.loads(current_obj, object_hook=float_hook)
                        if data and product_id in data:
                            return data[product_id]
                    except json.JSONDecodeError:
                        pass
                    current_obj = ""
        
        print(f"Product ID {product_id} not found")
        return None
            
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return None
    except Exception as e:
        print(f"Error: {str(e)}")
        return None


json_path = 'D:/OneDrive - StarHub Ltd/5. Scripts/product-attributes/output/Saree_attributes.json'
count = count_unique_products(json_path)
print(f"\nFinal count of unique products: {count}")

Parsing Statistics:
Total JSON objects found: 25
Failed to parse: 0
Unique products found: 25

First few product IDs found:
- 7372922781761
- 7372876546113
- 7372801835073
- 7372794265665
- 7372774015041

Final count of unique products: 25

In [9]:
product_temp = load_product_by_id(json_path, '7356361736257')
if product_temp:
    product_temp.pop('text_embedding', None)
    product_temp.pop('image_embedding', None)
product_temp

{'primary_color': 'Red',
 'primary_color_detailed': 'Crimson',
 'secondary_colors': [],
 'secondary_colors_detailed': [],
 'color_pairings_hex': ['#FF0033', '#FFD700', '#FFC0CB', '#800000', '#FF69B4'],
 'pattern': [],
 'saree_type': 'Banarasi',
 'border_width': 'Wide',
 'border_design': 'Zari',
 'border_design_details': ['Intricate zari work on border',
  'Traditional motifs in gold',
  'Scalloped edge design',
  'Contrast red and gold pattern',
  'Rich metallic sheen'],
 'pallu_design': 'Elaborate',
 'pre_draped': False,
 'material': 'Silk',
 'length': 6.3,
 'width': 1.1,
 'weight': 800,
 'care_instructions': 'Dry clean only. Store in a cool, dry place. Avoid direct sunlight.',
 'occasions': [],
 'embellishment_level': 'Medium',
 'embellishment': [],
 'embellishment_detailed': ['Gold zari woven polka dot pattern',
  'Intricate zari border work',
  'Metallic thread embroidery on pallu',
  'Subtle shimmering effect throughout'],
 'style': [],
 'brand_title': 'Red Dream',
 'title': 'Crimson Constellation: A Starry Night Saree',
 'description': "Embark on a celestial journey with our 'Crimson Constellation' saree. This Banarasi silk masterpiece marries the richness of deep crimson with the opulence of golden zari work, creating a mesmerizing polka dot pattern reminiscent of a starlit sky. The wide, elaborately designed border and pallu showcase intricate traditional motifs, elevating this saree to a work of art. Perfect for weddings, festivals, and high-profile events, this saree promises to make you the center of attention with its elegant drape and timeless appeal. A true embodiment of modern royalty, this saree is not just an outfit, but a statement of grace and sophistication.",
 'gender': 'Female',
 'age_group': 'Adult',
 'unique_design_element': ['Celestial-inspired golden polka dot pattern on rich crimson base',
  'Exquisite Banarasi silk with intricate zari work border',
  'Versatile design suitable for both traditional and modern styling'],
 'inference_time': 20.910067319869995,
 'model': 'claude-3-5-sonnet-20240620',
 'input_tokens': 4785,
 'output_tokens': 1157,
 'has_text_embedding': True,
 'has_image_embedding': True,
 'processed_at': '2025-03-13 13:28:16.649147'}

In [5]:
import asyncio
import logging
import os
from pathlib import Path
import yaml
import pandas as pd
from typing import Dict, Any, Tuple, List, Optional
from dotenv import load_dotenv
import argparse
from datetime import datetime

from src.factories.clothing_factory import ClothingFactory
from src.services.api_service import APIService
from src.services.attribute_generator import AttributeGenerator
from src.services.batch_processor import BatchProcessor
from src.utils.logging_utils import (
    setup_logging, 
    LoggingContext, 
    PerformanceMetrics,
    StructuredLogger
)
from src.services.product_standardizer import ProductStandardizer
from src.base.clothing_item import ClothingItem

In [6]:

async def process_product(
    product_data: Dict[str, Any],
    product_type: str,
    attribute_generator: AttributeGenerator
) -> Optional[Dict[str, Any]]:
    """Process a single product."""
    product_id = product_data.get("product_id", "unknown")
    
    # Create product-specific metrics
    product_metrics = PerformanceMetrics()
    product_metrics.checkpoint("start")
    
    # Create structured logger for this product
    product_logger = StructuredLogger(
        "product_processor",
        extra_fields={
            "product_id": product_id,
            "product_type": product_type
        }
    )
    
    product_logger.info(f"Processing product {product_id}")
    
    # Generate attributes using the API
    try:
        product_metrics.checkpoint("api_call_start")
        generated_attributes = await attribute_generator.generate_attributes(
            product_data=product_data,
            product_type=product_type
        )
        product_metrics.checkpoint("api_call_end")
        
        # Calculate API call duration
        api_duration = product_metrics.measure(
            "api_call", 
            "api_call_start", 
            "api_call_end"
        )
        
        if generated_attributes:
            product_logger.info(
                f"Successfully generated attributes for product {product_id}",
                extra={
                    "duration": api_duration,
                    "attribute_count": len(generated_attributes)
                }
            )
            return generated_attributes
        else:
            product_logger.error(
                f"Failed to generate attributes for product {product_id}",
                extra={"duration": api_duration}
            )
            return None
    except Exception as e:
        product_logger.error(
            f"Error processing product {product_id}: {str(e)}",
            extra={"error_type": type(e).__name__},
            exc_info=True
        )
        return None
    finally:
        # Log total processing time
        total_duration = product_metrics.measure("total")
        product_logger.info(
            "Product processing completed",
            extra={"total_duration": total_duration}
        )

In [ ]:
from src.utils.config_loader import ConfigManager
cf = ConfigManager
temp = cf.get_available_product_types()
temp
# product_config = ConfigManager.get_product_config('saree')
# defined_attributes = product_config.get('attributes', {})
# defined_attributes

In [4]:
ConfigManager.get_product_config('saree')['attributes']['brand']['default']

{'required': True,
 'data_type': 'string',
 'item_type': 'string',
 'default': 'suta',
 'in_search_context': True}

In [5]:
from src.base.clothing_item import ClothingItem
ClothingItem.build_search_context(product_data)

NameError: name 'product_data' is not defined

In [3]:
def test_prompt_loading():
    from pathlib import Path
    from src.services.attribute_generator import AttributeGenerator
    
    # Expanded config with required Cohere settings
    config = {
        "prompts": {
            "dir": "D:/OneDrive - StarHub Ltd/5. Scripts/product-attributes/config/prompts"  # Your actual path
        },
        "api": {
            "cohere": {
                "model": "embed-english-v3.0",  # or whatever model you're using
                "supported_operations": ["embed"]  # Add embed operation
            }
        }
    }
    
    # Create instance with minimal dependencies
    generator = AttributeGenerator(api_service=None, config=config)
    
    # Test prompt loading
    prompt = generator._load_prompt('saree')
    print(prompt)
    return prompt

# Run the test
prompt = test_prompt_loading()

You are a fashion expert specializing in Indian ethnic wear, particularly sarees.
Analyze this saree image and product information to generate detailed JSON data.

IMPORTANT GUIDELINES:
- Focus ONLY on the saree in the image, not any blouse or other garments shown
- Use the exact product name from the data for brand_title (e.g. if product name is "Green Dream", use that)
- Analyze colors ONLY from the saree itself, not from any accompanying blouse or accessories
- Be precise in identifying embellishments and patterns that are actually present on the saree
- STRICTLY use only the allowed values provided for each attribute
- Use material information from the product data, don't try to infer it from the image
- For ruffled designs, use "Others" as pattern and "Sequinned" as embellishment
- Color pairings MUST be 6-digit hex codes (e.g., "#FF0000", "#00FF00")
- Use the exact product URL from the data for product_url field

Requirements:
1. Colors & Patterns:
   - "primary_color": Identify and list the single most dominant color in the product as primary_color. primary_color MUST be one of: 'Black', 'White', 'Brown', 'Red', 'Yellow', 'Green', 'Blue', 'Pink', 'Orange', 'Purple', 'Grey', 'Gold', 'Silver', 'Beige', 'Maroon', 'Navy', 'Teal', 'Olive', 'Cyan', 'Magenta', 'Others' (ONLY for the saree)
   - "primary_color_hex": Provide the exact hex code for the primary color (e.g., #FF5733)
   - "primary_color_detailed": Identify and list the single most dominant color in the product as primary_color_detailed. primary_color_detailed MUST be one of: ColorDetailed (ONLY for the saree)
   - "secondary_colors": Identify and list the next most prominent colors in the product, secondary_colors MUST be one of: 'Black', 'White', 'Brown', 'Red', 'Yellow', 'Green', 'Blue', 'Pink', 'Orange', 'Purple', 'Grey', 'Gold', 'Silver', 'Beige', 'Maroon', 'Navy', 'Teal', 'Olive', 'Cyan', 'Magenta', 'Others' and ONLY for the saree
   - "secondary_color_hexes": Provide the exact hex code for each secondary color in a comma-separated python list format (e.g., #33FF57, #5733FF)
   - "secondary_colors_detailed": Identify and list the next most prominent colors from ONLY the saree, if any in a comma-separated python list format. For each secondary color, provide a closest matching secondary_colors_detailed from ColorDetailed enum
   - "secondary_colors_detailed_hex": REQUIRED - Provide the exact hex code for each secondary_colors_detailed in a comma-separated python list format. Must match the order of secondary_colors_detailed.
   - "color_pairings": List of complementary color hex codes that can be used to style the product in a comma-separated python list format. MUST be a list of EXACTLY 5 hex codes (e.g., ["#FF0000", "#00FF00", "#0000FF", "#FFFF00", "#FF00FF"])
   - "pattern": Describe the patterns only in SAREE in a comma-separated python list format. pattern MUST ONLY use these values: 'Abstract', 'Animal', 'Bandhani', 'Batik', 'Checked', 'Color Block', 'Digital Print', 'Embroidered', 'Floral', 'Foil Print', 'Geometric', 'Hand-painted', 'Ikat', 'Jamdani', 'Leheriya', 'Ombre', 'Paisley', 'Polka Dot', 'Screen Print', 'Sequined', 'Shibori', 'Solid', 'Striped', 'Tie-dye', 'Traditional Motif', 'Woven', 'Zari', 'Textured', 'Jacquard', 'Others' (based on patterns in saree ONLY). Make sure to include only patterns and not embellishments that are actually present in the saree.
   - If primary_color or secondary_colors are not found in the 'Black', 'White', 'Brown', 'Red', 'Yellow', 'Green', 'Blue', 'Pink', 'Orange', 'Purple', 'Grey', 'Gold', 'Silver', 'Beige', 'Maroon', 'Navy', 'Teal', 'Olive', 'Cyan', 'Magenta', 'Others', use "Others"
   - If pattern doesn't match exactly, use 'Others'
   - All color hex codes must be valid 6-digit formats (#RRGGBB)

2. Design Elements:
   - "saree_type": Must be one of: 'Banarasi', 'Bomkai Silk', 'Mysore Silk', 'Muga', 'Tussar', 'Khadi', 'Mangalagiri', 'Narayanpeth', 'Venkatgiri', 'Ilkal', 'Chanderi', 'Jamdani', 'Paithani', 'Patola', 'Sambalpuri', 'Bagru', 'Baluchari', 'Bandhani', 'Bhagalpuri', 'Dharamavaram', 'Gadwal', 'Kanjivaram', 'Kota', 'Maheshwari', 'Pochampally', 'Block Print', 'Ikat', 'Leheriya', 'Sungudi', 'Taant', 'Others'
   - "border_width": Must be one of: 'Narrow', 'Medium', 'Wide', 'Others'
   - "border_design": Must be one of: 'Contrast', 'Embroidered', 'Plain', 'Printed', 'Zari', 'Others'
   - "border_design_details": List 3-5 specific details of border design such as but limited to pattern, design, style of the border(e.g., ["Intricate zari work on border", "Geometric patterns in gold", "Ruffled Border", "Border with tassels"] )
   - "pallu_design": Must be one of: 'Contrast', 'Elaborate', 'Matching', 'Plain', 'Traditional', 'Others'
   - "pre_draped": Boolean indicating if the saree is pre-draped (True) or traditional draping required (False)

3. Material & Structure:
   - "material": MUST be one of: 'Silk', 'Cotton', 'Chiffon', 'Georgette', 'Banarasi', 'Kanjivaram', 'Chanderi', 'Tussar', 'Organza', 'Linen', 'Modal_Viscose', 'Others'. MUST use FIRST valid Material enum value found in brand's product description. Example: "Silk Cotton with Zari" → "Silk". If no exact matches in 'Silk', 'Cotton', 'Chiffon', 'Georgette', 'Banarasi', 'Kanjivaram', 'Chanderi', 'Tussar', 'Organza', 'Linen', 'Modal_Viscose', 'Others' found → 'Other'
   - "length": must be between 4.5-9.5 meters
   - "width": must be between 0.9-1.4 meters
   - "weight": must be between 300-1000 grams
   - "care_instructions": Care instructions for the saree from the brand's product description.

4. Usage & Style:
   - "occasions": select 2-4 occasions and they MUST ONLY use these values: 'Wedding Wear', 'Festive Wear', 'Casual Wear', 'Party Wear', 'Work Wear', 'Formal Events', 'Others'
   - "occasions_detailed": List 3-5 high-impact events for maximum visibility. Include Celebrity weddings/fashion weeks, Cultural festivals (Diwali, Onam, Durga Puja), Fusion events (pride parades, date nights, gallery openings), Royal gatherings/red carpet events. Format: Python list
   - "embellishment_level": embellishment_level MUST be one of: 'None', 'Light', 'Medium', 'Heavy'
   - "embellishment": embellishment MUST ONLY use these values: 'Stone', 'Zardozi', 'Mirror Work', 'Gota Patti', 'Aari Work', 'Beads', 'Chikankari', 'Embroidery', 'Mukaish', 'Phulkari', 'Schiffli', 'Sequinned', 'Zari', 'None', 'Others'
   - If embellishment doesn't match exactly, use the closest match or mention "None"
   - embellishment_detailed: embellishment_detailed MUST be a list of 3-5 detailed embellishments present in the saree and only if the saree has any embellishments. Detail any decorative elements or embellishments on the product in a comma-separated python list format for embellishment_detailed
   - "style": style MUST be one of: 'Casual', 'Festive', 'Indo-Western', 'Modern Traditional', 'Ethnic Fusion', 'Minimalist', 'Bohemian', 'Vintage', 'Elegant', 'Others'. Characterize the overall style of the product using 1-2 descriptors into a list format

5. Product Information:
   - "brand_title": Use the exact product name from column "Product Name" for brand_title
   - "title": A memorable and creative product title (30-60 characters) incorporating Indian culture, wordplay, and brand style (eg: 1. Bloom Bazaar, 2. Petal Pirouette, 3. Floral Rhapsody, 4. Blossom Breeze, 5. Botanical Bliss)
   - "description": A detailed product description (100-150 words) written from an expert perspective, emphasizing unique features, benefits, and selling points with the quirky title we generated now.

6. Coordinating Items:
   - "clothing": REQUIRED - Suggest EXACTLY 5 coordinate clothing items that would pair well with the main product. Consider:
     * Traditional options (e.g., blouses, cholis)
     * Contemporary options (e.g., crop tops, jackets)
     * Color coordination with the saree's primary and secondary colors
     * Style matching (traditional with traditional, modern with modern)
     * Occasion appropriateness
   - "accessories": REQUIRED - Suggest EXACTLY 5 accessories that enhance the look. Consider:
     * Jewelry (necklaces, earrings, bangles)
     * Hair accessories (pins, clips, tikkas)
     * Bags (clutches, potlis)
     * Color matching or complementary colors
     * Style consistency
   - "footwear": REQUIRED - Recommend EXACTLY 5 footwear options. Consider:
     * Traditional options (juttis, kolhapuris)
     * Modern options (heels, flats)
     * Comfort and occasion appropriateness
     * Color coordination
     * Style matching
   - "additional_apparel": REQUIRED - Suggest EXACTLY 3 additional items. Consider:
     * Layering pieces (shawls, jackets)
     * Weather-appropriate options
     * Style enhancement pieces
     * Color complementing items
   - "styling_suggestions": REQUIRED - Provide EXACTLY 3 specific outfit combinations using items from above categories. Each suggestion should:
     * Specify items from at least 3 categories
     * Include the occasion or setting
     * Consider the overall style theme
     * Ensure color coordination
     * Maintain style consistency

7. Target Audience:
   - "gender": MUST be from: 'Female', 'Male', 'Unisex'
   - "age_group": MUST be from: 'Adult', 'Teen', 'Kids', 'Senior'

8. Unique Selling Points:
   - unique_design_element: List 1-3 distinct selling points that make this item unique. Focus on:
     * Eye-catching design elements (e.g., "Signature scalloped border with gold threadwork")
     * Innovative fabric technology (e.g., "Wrinkle-resistant silk for easy maintenance")
     * Versatile styling (e.g., "Reversible design offers two looks in one saree")
     * Fashion trends (e.g., "On-trend ombré effect fading from navy to silver")
     * Craftsmanship (e.g., "Hand-embroidered peacock motif takes 72 hours to complete")

VALIDATION RULES:
- All enum values must match exactly with the provided options
- No custom values or variations are allowed
- For occasions, use "Bridal/Wedding" instead of "Wedding" or "Wedding Wear"
- For materials, use only the standard options provided (e.g., use "Silk" for artificial silk)
- For patterns, use "Others" if the exact pattern is not in the list
- For embellishments, choose the closest match from allowed values
- All color hex codes must be 6 digits (e.g., "#FF0000" not "#F00")
- color_pairings must be a list of EXACTLY 5 hex codes
- coordinating_items MUST NOT contain empty arrays - each category must have the minimum number of suggestions specified

Return only valid JSON wrapped in <json></json> tags.

In [13]:
from src.factories.clothing_factory import ClothingFactory
from src.base.utils import EnumRegistry

In [14]:
ClothingFactory.initialize()
raw_available_types = ClothingFactory.get_available_types()

In [3]:
from src.base.utils import EnumRegistry
from src.utils.config_loader import ConfigManager

# Debug config loading
config_manager = ConfigManager.get_instance()
print("Base config:", config_manager.get_base_config())
print("Available products:", config_manager.get_available_product_types())
print("Saree config:", config_manager.get_product_config('saree'))

# Get and inspect registry
registry = EnumRegistry.get_instance()
print("\nRegistry state:")
print("Product types:", registry._product_types)
print("Base mappings:", registry._base_mappings)
print("Enum mappings:", registry._enum_mappings)

# Get saree mappings
mappings = registry.get_enum_mappings('kurta')
print("\nkurta mappings:", mappings)

Base config: {'api': {'anthropic': {'model': 'claude-3-5-sonnet-20240620', 'max_retries': 3, 'base_delay': 4, 'max_delay': 60, 'concurrent_limit': 3, 'batch_size': 5, 'pricing': {'base_input': 3.0, 'cache_write': 3.75, 'cache_read': 1.5, 'output': 15.0}}, 'cohere': {'model': 'embed-english-v3.0', 'max_retries': 3, 'base_delay': 4, 'max_delay': 60}}, 'paths': {'input': {'product_data': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/processed_dataframe.csv', 'images_dir': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images'}, 'output': {'base_dir': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/product_attributes/output', 'structure': {'attributes': '{product_type}/attributes', 'images': '{product_type}/images'}, 'logs_dir': 'logs'}}, 'prompts': {'dir': 'config/prompts', 'system_temperature': 0.1, 'max_tokens': 4096}, 'attributes': {'brand': {'required': True, 'data_type': 'string', 'item_type': 'string', 'default': 'suta', 'in_search_context': False}, 'brand_title': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': False}, 'title': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': True}, 'description': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': True}, 'price': {'required': True, 'data_type': 'float', 'item_type': 'float', 'min': 0, 'in_search_context': False}, 'primary_color': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'Color', 'threshold': 1, 'in_search_context': True}, 'primary_color_hex': {'required': True, 'data_type': 'string', 'item_type': 'string', 'pattern': '^#([A-Fa-f0-9]{6})$', 'in_search_context': False}, 'primary_color_detailed': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'ColorDetailed', 'threshold': 0.8, 'in_search_context': True}, 'secondary_colors': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Color', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'secondary_color_hex': {'required': True, 'data_type': 'list', 'item_type': 'string', 'max_length': 3, 'pattern': '^#([A-Fa-f0-9]{6})$', 'in_search_context': False}, 'secondary_colors_detailed_hex': {'required': True, 'data_type': 'list', 'item_type': 'string', 'pattern': '^#([A-Fa-f0-9]{6})$', 'max_length': 3, 'in_search_context': False}, 'secondary_colors_detailed': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'ColorDetailed', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'pattern': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Pattern', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'material': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'Material', 'threshold': 0.8, 'in_search_context': True}, 'embellishment': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Embellishment', 'max_length': 5, 'threshold': 0.8, 'in_search_context': True}, 'embellishment_level': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'EmbellishmentLevel', 'threshold': 0.8, 'in_search_context': True}, 'embellishment_detailed': {'required': True, 'data_type': 'list', 'item_type': 'string', 'max_length': 5, 'in_search_context': True}, 'occasions': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Occasion', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'occasions_detailed': {'required': True, 'data_type': 'list', 'item_type': 'string', 'max_length': 5, 'in_search_context': True}, 'style': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Style', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'care_instructions': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': True}, 'size': {'required': True, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'unique_design_element': {'required': True, 'data_type': 'list', 'item_type': 'string', 'min_length': 1, 'max_length': 3, 'in_search_context': True}, 'gender': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Gender', 'default': ['FEMALE'], 'threshold': 1.0, 'in_search_context': False}, 'age_group': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'AgeGroup', 'default': ['ADULT'], 'threshold': 1.0, 'in_search_context': False}, 'coordinating_items': {'required': True, 'data_type': 'object', 'item_type': 'object', 'properties': {'clothing': {'data_type': 'list', 'item_type': 'string', 'max_length': 5}, 'accessories': {'data_type': 'list', 'item_type': 'string', 'max_length': 5}, 'footwear': {'data_type': 'list', 'item_type': 'string', 'max_length': 5}, 'additional_apparel': {'data_type': 'list', 'item_type': 'string', 'max_length': 3}, 'styling_suggestions': {'data_type': 'list', 'item_type': 'string', 'max_length': 3}}, 'in_search_context': False}, 'product_image_link': {'required': True, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'product_url': {'required': True, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'search_context': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': False}, 'text_embedding': {'required': True, 'data_type': 'list', 'item_type': 'float', 'in_search_context': False}, 'image_embedding': {'required': True, 'data_type': 'list', 'item_type': 'float', 'in_search_context': False}}, 'validation_errors': {'required': False, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'logging': {'level': 'INFO', 'format': '%(asctime)s - %(levelname)s - [%(name)s:%(lineno)d] - %(message)s', 'handlers': [{'type': 'file', 'filename': 'processing_{timestamp}.log'}, {'type': 'stream'}]}, 'caching': {'backend': 'redis', 'host': 'localhost', 'port': 6379, 'db': 0, 'prefix': 'prod_attr:'}, 'search_context': {'include_base_attributes': ['title', 'description', 'price', 'primary_color', 'primary_color_detailed', 'secondary_colors', 'secondary_colors_detailed', 'pattern', 'material', 'embellishment', 'embellishment_level', 'embellishment_detailed', 'occasions', 'occasion_detailed', 'style', 'care_instructions', 'size', 'unique_design_element', 'gender', 'age_group', 'coordinating_items'], 'format_rules': {'list_attributes': {'join_with': ', '}, 'enum_attributes': {'use_value': True}, 'boolean_attributes': {'true_format': '{attr_name}: Yes', 'false_format': None}, 'coordinating_items': {'format': '{category}: {items}', 'items_join': ', ', 'categories_join': '; '}}}, 'category_standardization': {'patterns': [{'name': 'Saree', 'matches': ['saree', 'sari', 'garage_saree', 'saree with blouse piece', 'reversible saree', 'ready to wear']}, {'name': 'Blouse', 'matches': ['blouse', 'garage_blouse']}, {'name': 'Kurta', 'matches': ['kurta set', 'kurta']}, {'name': 'Lehenga', 'matches': ['lehenga set', 'lehengas', 'semi stitched lehenga set', 'skirt, blouse and dupatta']}, {'name': 'Dupatta', 'matches': ['dupatta', 'stole', 'shawl']}, {'name': 'Underskirt', 'matches': ['underskirt', 'petticoat']}, {'name': 'Co-ord Set', 'matches': ['co-ord set', 'co-ord']}, {'name': 'Combo Sets', 'matches': ['combo of \\d+', 'combo']}, {'name': 'Dress', 'matches': ['dress', 'pantsuit set', 'lounge wear']}, {'name': 'Accessories', 'matches': ['accessories', 'earrings', 'scarf', 'neckpiece', 'scrunchies']}, {'name': 'Fabric', 'matches': ['fabric', 'swaddle', 'curtains', 'bed linen']}, {'name': 'Shirt', 'matches': ['shirt', 'shirts & tops']}, {'name': 'Trouser', 'matches': ['trouser', 'pants', 'dhoti']}, {'name': 'Jacket', 'matches': ['jacket', 'long jacket', 'short jacket', 'overcoat']}, {'name': 'Home Textiles', 'matches': ['quilts & comforters', 'bunting', 'table runner']}, {'name': 'Gift Items', 'matches': ['gift', 'gift box', 'gift wrapping', 'gift cards']}, {'name': 'Rakhi', 'matches': ['rakhi', 'lumba rakhi']}], 'default_strategy': 'title_case'}}
Available products: ['kurta', 'dress', 'trouser', 'dupatta', 'shirt', 'blouse', 'lehenga', 'saree']
Saree config: {'api': {'anthropic': {'model': 'claude-3-5-sonnet-20240620', 'max_retries': 3, 'base_delay': 4, 'max_delay': 60, 'concurrent_limit': 3, 'batch_size': 5, 'pricing': {'base_input': 3.0, 'cache_write': 3.75, 'cache_read': 1.5, 'output': 15.0}}, 'cohere': {'model': 'embed-english-v3.0', 'max_retries': 3, 'base_delay': 4, 'max_delay': 60}}, 'paths': {'input': {'product_data': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/processed_dataframe.csv', 'images_dir': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/uplyft-shopify-scraper/data/02_intermediate/suta/images'}, 'output': {'base_dir': '/Users/aswinsreenivas/Projects/D2C Search Engine/uplyft_server/product_attributes/output', 'structure': {'attributes': '{product_type}/attributes', 'images': '{product_type}/images'}, 'logs_dir': 'logs'}}, 'prompts': {'dir': 'config/prompts', 'system_temperature': 0.1, 'max_tokens': 4096}, 'attributes': {'brand': {'required': True, 'data_type': 'string', 'item_type': 'string', 'default': 'suta', 'in_search_context': False}, 'brand_title': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': False}, 'title': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': True}, 'description': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': True}, 'price': {'required': True, 'data_type': 'float', 'item_type': 'float', 'min': 0, 'in_search_context': False}, 'primary_color': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'Color', 'threshold': 1, 'in_search_context': True}, 'primary_color_hex': {'required': True, 'data_type': 'string', 'item_type': 'string', 'pattern': '^#([A-Fa-f0-9]{6})$', 'in_search_context': False}, 'primary_color_detailed': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'ColorDetailed', 'threshold': 0.8, 'in_search_context': True}, 'secondary_colors': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Color', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'secondary_color_hex': {'required': True, 'data_type': 'list', 'item_type': 'string', 'max_length': 3, 'pattern': '^#([A-Fa-f0-9]{6})$', 'in_search_context': False}, 'secondary_colors_detailed_hex': {'required': True, 'data_type': 'list', 'item_type': 'string', 'pattern': '^#([A-Fa-f0-9]{6})$', 'max_length': 3, 'in_search_context': False}, 'secondary_colors_detailed': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'ColorDetailed', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'pattern': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Pattern', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'material': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'Material', 'threshold': 0.8, 'in_search_context': True}, 'embellishment': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Embellishment', 'max_length': 5, 'threshold': 0.8, 'in_search_context': True}, 'embellishment_level': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'EmbellishmentLevel', 'threshold': 0.8, 'in_search_context': True}, 'embellishment_detailed': {'required': True, 'data_type': 'list', 'item_type': 'string', 'max_length': 5, 'in_search_context': True}, 'occasions': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Occasion', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'occasions_detailed': {'required': True, 'data_type': 'list', 'item_type': 'string', 'max_length': 5, 'in_search_context': True}, 'style': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Style', 'max_length': 3, 'threshold': 0.8, 'in_search_context': True}, 'care_instructions': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': True}, 'size': {'required': True, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'unique_design_element': {'required': True, 'data_type': 'list', 'item_type': 'string', 'min_length': 1, 'max_length': 3, 'in_search_context': True}, 'gender': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'Gender', 'default': ['FEMALE'], 'threshold': 1.0, 'in_search_context': False}, 'age_group': {'required': True, 'data_type': 'list', 'item_type': 'enum', 'allowed_values': 'AgeGroup', 'default': ['ADULT'], 'threshold': 1.0, 'in_search_context': False}, 'coordinating_items': {'required': True, 'data_type': 'object', 'item_type': 'object', 'properties': {'clothing': {'data_type': 'list', 'item_type': 'string', 'max_length': 5}, 'accessories': {'data_type': 'list', 'item_type': 'string', 'max_length': 5}, 'footwear': {'data_type': 'list', 'item_type': 'string', 'max_length': 5}, 'additional_apparel': {'data_type': 'list', 'item_type': 'string', 'max_length': 3}, 'styling_suggestions': {'data_type': 'list', 'item_type': 'string', 'max_length': 3}}, 'in_search_context': False}, 'product_image_link': {'required': True, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'product_url': {'required': True, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'search_context': {'required': True, 'data_type': 'string', 'item_type': 'string', 'in_search_context': False}, 'text_embedding': {'required': True, 'data_type': 'list', 'item_type': 'float', 'in_search_context': False}, 'image_embedding': {'required': True, 'data_type': 'list', 'item_type': 'float', 'in_search_context': False}, 'saree_type': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'SareeType', 'threshold': 0.8, 'in_search_context': True}, 'border_width': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'BorderWidth', 'threshold': 0.8, 'in_search_context': True}, 'border_design': {'required': True, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'BorderDesign', 'threshold': 0.8, 'in_search_context': True}, 'border_design_details': {'required': True, 'data_type': 'list', 'item_type': 'string', 'min_length': 3, 'max_length': 5, 'in_search_context': True}, 'pallu_design': {'required': True, 'data_type': 'list', 'item_type': 'string', 'allowed_values': 'PalluDesign', 'threshold': 0.8, 'in_search_context': True}, 'length': {'required': True, 'data_type': 'float', 'item_type': 'float', 'min': 0, 'max': 12, 'unit': 'meters', 'in_search_context': False}, 'width': {'required': True, 'data_type': 'float', 'item_type': 'float', 'min': 0.9, 'max': 1.4, 'unit': 'meters', 'in_search_context': False}, 'weight': {'required': True, 'data_type': 'float', 'item_type': 'float', 'min': 300, 'max': 1000, 'unit': 'grams', 'in_search_context': False}, 'color_pairings_hex': {'required': True, 'data_type': 'list', 'item_type': 'string', 'pattern': '^#([A-Fa-f0-9]{6})$', 'length': 5, 'in_search_context': False}, 'blouse_included': {'required': True, 'data_type': 'boolean', 'item_type': 'boolean', 'default': False, 'in_search_context': False}, 'blouse_material': {'required': False, 'data_type': 'string', 'item_type': 'enum', 'allowed_values': 'Material', 'threshold': 0.8, 'in_search_context': False}, 'pre_draped': {'required': False, 'data_type': 'boolean', 'item_type': 'boolean', 'default': False, 'in_search_context': False}, 'reversible': {'required': False, 'data_type': 'boolean', 'item_type': 'boolean', 'default': False, 'in_search_context': False}, 'styling_suggestions': {'required': True, 'data_type': 'string', 'item_type': 'string', 'max_length': 3, 'in_search_context': False}}, 'validation_errors': {'required': False, 'data_type': 'list', 'item_type': 'string', 'in_search_context': False}, 'logging': {'level': 'INFO', 'format': '%(asctime)s - %(levelname)s - [%(name)s:%(lineno)d] - %(message)s', 'handlers': [{'type': 'file', 'filename': 'processing_{timestamp}.log'}, {'type': 'stream'}]}, 'caching': {'backend': 'redis', 'host': 'localhost', 'port': 6379, 'db': 0, 'prefix': 'prod_attr:'}, 'search_context': {'include_base_attributes': ['title', 'description', 'price', 'primary_color', 'primary_color_detailed', 'secondary_colors', 'secondary_colors_detailed', 'pattern', 'material', 'embellishment', 'embellishment_level', 'embellishment_detailed', 'occasions', 'occasion_detailed', 'style', 'care_instructions', 'size', 'unique_design_element', 'gender', 'age_group', 'coordinating_items'], 'format_rules': {'list_attributes': {'join_with': ', '}, 'enum_attributes': {'use_value': True}, 'boolean_attributes': {'true_format': '{attr_name}: Yes', 'false_format': None}, 'coordinating_items': {'format': '{category}: {items}', 'items_join': ', ', 'categories_join': '; '}}}, 'category_standardization': {'patterns': [{'name': 'Saree', 'matches': ['saree', 'sari', 'garage_saree', 'saree with blouse piece', 'reversible saree', 'ready to wear']}, {'name': 'Blouse', 'matches': ['blouse', 'garage_blouse']}, {'name': 'Kurta', 'matches': ['kurta set', 'kurta']}, {'name': 'Lehenga', 'matches': ['lehenga set', 'lehengas', 'semi stitched lehenga set', 'skirt, blouse and dupatta']}, {'name': 'Dupatta', 'matches': ['dupatta', 'stole', 'shawl']}, {'name': 'Underskirt', 'matches': ['underskirt', 'petticoat']}, {'name': 'Co-ord Set', 'matches': ['co-ord set', 'co-ord']}, {'name': 'Combo Sets', 'matches': ['combo of \\d+', 'combo']}, {'name': 'Dress', 'matches': ['dress', 'pantsuit set', 'lounge wear']}, {'name': 'Accessories', 'matches': ['accessories', 'earrings', 'scarf', 'neckpiece', 'scrunchies']}, {'name': 'Fabric', 'matches': ['fabric', 'swaddle', 'curtains', 'bed linen']}, {'name': 'Shirt', 'matches': ['shirt', 'shirts & tops']}, {'name': 'Trouser', 'matches': ['trouser', 'pants', 'dhoti']}, {'name': 'Jacket', 'matches': ['jacket', 'long jacket', 'short jacket', 'overcoat']}, {'name': 'Home Textiles', 'matches': ['quilts & comforters', 'bunting', 'table runner']}, {'name': 'Gift Items', 'matches': ['gift', 'gift box', 'gift wrapping', 'gift cards']}, {'name': 'Rakhi', 'matches': ['rakhi', 'lumba rakhi']}], 'default_strategy': 'title_case'}}

Registry state:
Product types: {'kurta', 'dress', 'trouser', 'dupatta', 'saree', 'blouse', 'lehenga', 'shirt'}
Base mappings: {'primary_color': <enum 'Color'>, 'primary_color_detailed': <enum 'ColorDetailed'>, 'secondary_colors': <enum 'Color'>, 'secondary_colors_detailed': <enum 'ColorDetailed'>, 'pattern': <enum 'Pattern'>, 'material': <enum 'Material'>, 'embellishment': <enum 'Embellishment'>, 'embellishment_level': <enum 'EmbellishmentLevel'>, 'occasions': <enum 'Occasion'>, 'style': <enum 'Style'>, 'gender': <enum 'Gender'>, 'age_group': <enum 'AgeGroup'>}

In [28]:
c = ClothingFactory()
c.create_product('Jacket')

Using base ClothingItem for undefined type: Jacket
No configuration found for product type: jacket
Error creating Jacket: WOMEN

In [29]:
 available_types = [
                    ClothingItem.standardize_category(t) 
                    for t in ClothingFactory.get_available_types()
                ]

In [33]:
len(df['standardized_category'].unique())

29